"""
Theme synchronizer: Updates config files for Rofi, Polybar, i3, Kitty, and Dunst.
"""
import os
import subprocess
from .themes import THEMES, THEME_PREF_FILE

def apply_global_theme(theme_key):
    if theme_key not in THEMES:
        return False

    t = THEMES[theme_key]

    # 1. Save Preference File
    try:
        os.makedirs(os.path.dirname(THEME_PREF_FILE), exist_ok=True)
        with open(THEME_PREF_FILE, "w") as f:
            f.write(theme_key)
    except Exception:
        pass

    # 2. Update Rofi Colors (colors.rasi)
    rofi_colors = f"""/**
 * Global Theme Colors for Rofi
 * Auto-generated by Theme Switcher ({t["name"]})
 **/

* {{
    bg:             {t["bg_alpha_rofi"]};
    surface0:       {t["surface0_alpha_rofi"]};
    surface1:       {t["surface1"]};
    border-col:     {t["accent"]};
    accent:         {t["accent"]};
    accent-contrast:{t["accent_contrast"]};
    mauve:          {t["accent"]};
    fg:             {t["fg"]};
    subtext:        {t["subtext"]};
    overlay:        {t["overlay"]};
    blue:           {t["blue"]};
    red:            {t["red"]};
    green:          {t["green"]};
    yellow:         {t["yellow"]};
    crust:          {t["crust"]};
}}
"""
    for rofi_dir in [os.path.expanduser("~/.config/rofi"), os.path.expanduser("~/i3-dotfiles/.config/rofi")]:
        if os.path.isdir(rofi_dir):
            try:
                with open(os.path.join(rofi_dir, "colors.rasi"), "w") as f:
                    f.write(rofi_colors)
            except Exception:
                pass

    # 3. Update Polybar Colors (colors.ini)
    polybar_colors = f""";==========================================================
; Global Theme Colors for Polybar
; Auto-generated by Theme Switcher ({t["name"]})
;==========================================================

[colors]
base = {t["bg"]}
mantle = {t["mantle"]}
crust = {t["crust"]}
surface0 = {t["surface0"]}
surface1 = {t["surface1"]}
surface2 = {t["surface2"]}
text = {t["fg"]}
subtext = {t["subtext"]}
accent = {t["accent"]}
accent_secondary = {t["accent_secondary"]}
accent_contrast = {t["accent_contrast"]}
mauve = {t["accent"]}
pink = {t["pink"]}
red = {t["red"]}
peach = {t["peach"]}
yellow = {t["yellow"]}
green = {t["green"]}
teal = {t["teal"]}
sapphire = {t["accent_secondary"]}
blue = {t["blue"]}
lavender = {t["lavender"]}
transparent = #00000000
"""
    for pb_dir in [os.path.expanduser("~/.config/polybar"), os.path.expanduser("~/i3-dotfiles/.config/polybar")]:
        if os.path.isdir(pb_dir):
            try:
                with open(os.path.join(pb_dir, "colors.ini"), "w") as f:
                    f.write(polybar_colors)
            except Exception:
                pass

    # 4. Update i3 Colors (theme.conf)
    i3_colors = f"""# Global Theme Colors for i3wm
# Auto-generated by Theme Switcher ({t["name"]})
# class                 border  bground text    indicator child_border
client.focused          {t["accent"]} {t["bg"]} {t["fg"]} {t["lavender"]} {t["accent"]}
client.focused_inactive {t["surface1"]} {t["bg"]} {t["subtext"]} {t["surface1"]} {t["surface1"]}
client.unfocused        {t["surface0"]} {t["bg"]} {t["overlay"]} {t["surface0"]} {t["surface0"]}
client.urgent           {t["red"]} {t["bg"]} {t["red"]} {t["red"]} {t["red"]}
client.placeholder      {t["mantle"]} {t["mantle"]} {t["fg"]} {t["mantle"]} {t["mantle"]}
client.background       {t["bg"]}
"""
    for i3_dir in [os.path.expanduser("~/.config/i3"), os.path.expanduser("~/i3-dotfiles/.config/i3")]:
        if os.path.isdir(i3_dir):
            try:
                with open(os.path.join(i3_dir, "theme.conf"), "w") as f:
                    f.write(i3_colors)
            except Exception:
                pass

    # 5. Update Kitty Colors (theme.conf)
    kitty_colors = f"""# Kitty Theme - Auto-generated by Theme Switcher ({t["name"]})
foreground              {t["fg"]}
background              {t["bg"]}
selection_foreground    {t["bg"]}
selection_background    {t["selection_bg"]}

cursor                  {t["accent"]}
cursor_text_color       {t["bg"]}

url_color               {t["accent_secondary"]}

active_border_color     {t["accent"]}
inactive_border_color   {t["overlay"]}
bell_border_color       {t["yellow"]}

active_tab_foreground   {t["accent_contrast"]}
active_tab_background   {t["accent"]}
inactive_tab_foreground {t["fg"]}
inactive_tab_background {t["mantle"]}
tab_bar_background      {t["crust"]}

mark1_foreground {t["bg"]}
mark1_background {t["lavender"]}
mark2_foreground {t["bg"]}
mark2_background {t["accent"]}
mark3_foreground {t["bg"]}
mark3_background {t["teal"]}

# black
color0 {t["surface1"]}
color8 {t["surface2"]}

# red
color1 {t["red"]}
color9 {t["red"]}

# green
color2  {t["green"]}
color10 {t["green"]}

# yellow
color3  {t["yellow"]}
color11 {t["yellow"]}

# blue
color4  {t["accent_secondary"]}
color12 {t["accent_secondary"]}

# magenta
color5  {t["pink"]}
color13 {t["pink"]}

# cyan
color6  {t["teal"]}
color14 {t["teal"]}

# white
color7  {t["fg"]}
color15 {t["subtext"]}
"""
    for k_dir in [os.path.expanduser("~/.config/kitty"), os.path.expanduser("~/i3-dotfiles/.config/kitty")]:
        if os.path.isdir(k_dir):
            try:
                with open(os.path.join(k_dir, "theme.conf"), "w") as f:
                    f.write(kitty_colors)
            except Exception:
                pass

    # 6. Update Dunst (dunstrc)
    dunstrc_content = f"""[global]
    monitor = 0
    follow = mouse
    width = 320
    height = 250
    origin = top-right
    offset = 15x45
    scale = 0
    notification_limit = 5
    progress_bar = true
    progress_bar_height = 8
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 300
    indicate_hidden = yes
    transparency = 0
    separator_height = 2
    padding = 12
    horizontal_padding = 12
    text_icon_padding = 10
    frame_width = 2
    frame_color = "{t["accent"]}"
    gap_size = 6
    separator_color = frame
    sort = yes
    font = JetBrainsMono Nerd Font 10
    line_height = 0
    markup = full
    format = "<b>%s</b>\\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes
    enable_recursive_icon_lookup = true
    icon_position = left
    min_icon_size = 24
    max_icon_size = 48
    corner_radius = 12
    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

[urgency_low]
    background = "{t["bg"]}"
    foreground = "{t["fg"]}"
    frame_color = "{t["accent_secondary"]}"
    timeout = 5

[urgency_normal]
    background = "{t["bg"]}"
    foreground = "{t["fg"]}"
    frame_color = "{t["accent"]}"
    timeout = 7

[urgency_critical]
    background = "{t["bg"]}"
    foreground = "{t["fg"]}"
    frame_color = "{t["red"]}"
    timeout = 0
"""
    for d_dir in [os.path.expanduser("~/.config/dunst"), os.path.expanduser("~/i3-dotfiles/.config/dunst")]:
        if os.path.isdir(d_dir):
            try:
                with open(os.path.join(d_dir, "dunstrc"), "w") as f:
                    f.write(dunstrc_content)
            except Exception:
                pass

    # 7. Update Lockscreen Theme Colors (lock-colors)
    lock_colors = f"""# Global Theme Colors for i3lock
INSIDE_COLOR="{t['bg'].lstrip('#')}bb"
RING_COLOR="{t['accent'].lstrip('#')}ff"
VER_COLOR="{t['blue'].lstrip('#')}ff"
WRONG_COLOR="{t['red'].lstrip('#')}ff"
KEYHL_COLOR="{t['green'].lstrip('#')}ff"
BSHL_COLOR="{t['peach'].lstrip('#')}ff"
TIME_COLOR="{t['fg'].lstrip('#')}ff"
DATE_COLOR="{t['subtext'].lstrip('#')}ff"
VERIF_TEXT_COLOR="{t['accent_contrast'].lstrip('#')}ff"
WRONG_TEXT_COLOR="{t['accent_contrast'].lstrip('#')}ff"
"""
    for i3_dir in [os.path.expanduser("~/.config/i3"), os.path.expanduser("~/i3-dotfiles/.config/i3")]:
        if os.path.isdir(i3_dir):
            try:
                with open(os.path.join(i3_dir, "lock-colors"), "w") as f:
                    f.write(lock_colors)
            except Exception:
                pass

    # 8. Sync GTK color-scheme & dark preference
    is_light = (theme_key == "light")
    scheme = "prefer-light" if is_light else "prefer-dark"
    dark_flag = "0" if is_light else "1"
    try:
        subprocess.Popen(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme], stderr=subprocess.DEVNULL)
    except Exception:
        pass
    for gtk_dir in [os.path.expanduser("~/.config/gtk-3.0"), os.path.expanduser("~/.config/gtk-4.0")]:
        settings_file = os.path.join(gtk_dir, "settings.ini")
        if os.path.exists(settings_file):
            try:
                with open(settings_file, "r") as sf:
                    content = sf.read()
                import re
                new_content = re.sub(r"gtk-application-prefer-dark-theme\s*=\s*\d+", f"gtk-application-prefer-dark-theme = {dark_flag}", content)
                with open(settings_file, "w") as sf:
                    sf.write(new_content)
            except Exception:
                pass

    # 9. Live reload services
    subprocess.Popen(["i3-msg", "reload"], stderr=subprocess.DEVNULL)
    launch_script = os.path.expanduser("~/.config/polybar/launch.sh")
    if os.path.exists(launch_script):
        subprocess.Popen([launch_script], stderr=subprocess.DEVNULL)
    subprocess.Popen(["killall", "-SIGUSR1", "kitty"], stderr=subprocess.DEVNULL)
    subprocess.Popen(["killall", "-q", "dunst"], stderr=subprocess.DEVNULL)
    subprocess.Popen(["dunst"], stderr=subprocess.DEVNULL)

    # Dunst notification
    subprocess.Popen([
        "dunstify", "-a", "theme_switcher",
        "-h", "string:x-dunst-stack-tag:theme_switcher",
        "-i", "preferences-desktop-theme-symbolic",
        "-t", "1500", "-u", "low",
        "Theme Switched", f"Active Theme: {t['name']}"
    ], stderr=subprocess.DEVNULL)

    return True
