#!/bin/sh
# ==========================================================
# xinitrc for startx / xinit session
# ==========================================================

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f "$sysresources" ]; then
    xrdb -merge "$sysresources"
fi

if [ -f "$sysmodmap" ]; then
    xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Source environment and GTK themes
if [ -f "$HOME/.xprofile" ]; then
    . "$HOME/.xprofile"
fi

# Start window manager
exec i3
